[package]
name = "greateshot"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-protocols = { version = "0.29.5", default-features = false, features = [
	"unstable_protocols",
	"client",
] }
#wayland-protocols = { version = "=0.30.0-beta.13", features = ["client", "unstable"] }


wayland-protocols-wlr = { version = "0.1.0-beta.13", default-features = false, features = [
	"client",
] }
sctk = { git = "https://github.com/Smithay/client-toolkit", package = "smithay-client-toolkit", features = [
	"calloop",
] }
wayland-client = "0.29.5"
#wayland-client = "=0.30.0-beta.13"

image = { version = "0.24", default-features = false, features = [
	"jpeg",
	"png",
	"pnm",
] }

env_logger = { version = "0.9.0", default-features = false, features = [
	"atty",
	"termcolor",
] }

log = "0.4.17"
nix = "0.26.0"
memmap2 = "0.5.8"
slint = "0.3.2"

[build-dependencies]
slint-build = "0.3.2"
