[package]
name = "haruhishot"
version = "0.3.3"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-protocols = { version = "0.30.0", default-features = false, features = [
	"unstable",
	"client",
] }
#wayland-protocols = { version = "=0.30.0-beta.13", features = ["client", "unstable"] }


wayland-protocols-wlr = { version = "0.1.0", default-features = false, features = [
	"client",
] }
wayland-client = "0.30"
#wayland-client = "=0.30.0-beta.13"

image = { version = "0.24", default-features = false, features = [
	"jpeg",
	"png",
	"pnm",
] }

nix = "0.26.2"
memmap2 = "0.5.9"

# in the feature
slint = { version = "0.3.5", optional = true }

tracing-subscriber = "0.3.16"
tracing = "0.1.37"
clap = "4.1.6"
once_cell = "1.17.1"

dialoguer = { version = "0.10.3", features = ["fuzzy-select"] }

notify-rust = { version = "4.8.0", optional = true, features = ["images"] }

# impl it in the feature
[build-dependencies]
slint-build = { version = "0.3.5", optional = true }

[features]
notify = ["notify-rust"]
gui = ["slint", "slint-build"]
