name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install wlroots qt5-default libwayland-dev -y
    - name: nofeature
      run: cargo build --verbose
    - name: notifyfeature
      run: cargo build --features notify
    - name: guifeature
      run: cargo build --features gui
    - name: allfeatue
      run: cargo build --features gui --features notify
    - name: Run tests
      run: cargo test --verbose
